services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\DependencyInjection\EnvVarProcessor:
    tags: ['container.env_var_processor']

  TYPO3\CMS\Core\Configuration\SiteConfiguration:
    arguments:
      $configPath: "%env(TYPO3:configPath)%/sites"

  TYPO3\CMS\Core\Package\PackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\FailsafePackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Package\UnitTestPackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Http\MiddlewareDispatcher:
    autoconfigure: false

  TYPO3\CMS\Core\Database\Schema\SqlReader:
    public: true

  # EventListeners
  TYPO3\CMS\Core\Compatibility\Slot\PostInitializeMailer:
    tags:
      - { name: event.listener,
          identifier: 'legacy-slot',
          event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent }

  # Core caches, cache.core and cache.assets are injected as early
  # entries in TYPO3\CMS\Core\Core\Bootstrap and therefore omitted here
  cache.hash:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['hash']

  cache.pages:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pages']

  cache.pagesection:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pagesection']

  cache.runtime:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['runtime']

  cache.rootline:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['rootline']

  cache.imagesizes:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['imagesizes']

  cache.l10n:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['l10n']

  # Interface implementations
  Psr\EventDispatcher\EventDispatcherInterface:
    alias: TYPO3\CMS\Core\EventDispatcher\EventDispatcher
    public: true
  Psr\Http\Client\ClientInterface:
    alias: TYPO3\CMS\Core\Http\Client
    public: true
  Psr\Http\Message\RequestFactoryInterface:
    alias: TYPO3\CMS\Core\Http\RequestFactory
    public: true
  Psr\Http\Message\ResponseFactoryInterface:
    alias: TYPO3\CMS\Core\Http\ResponseFactory
    public: true
  Psr\Http\Message\ServerRequestFactoryInterface:
    alias: TYPO3\CMS\Core\Http\ServerRequestFactory
    public: true
  Psr\Http\Message\StreamFactoryInterface:
    alias: TYPO3\CMS\Core\Http\StreamFactory
    public: true
  Psr\Http\Message\UploadedFileFactoryInterface:
    alias: TYPO3\CMS\Core\Http\UploadedFileFactory
    public: true
  Psr\Http\Message\UriFactoryInterface:
    alias: TYPO3\CMS\Core\Http\UriFactory
    public: true
  GuzzleHttp\ClientInterface:
    alias: GuzzleHttp\Client
    public: true

  # External dependencies
  GuzzleHttp\Client:
    factory: ['TYPO3\CMS\Core\Http\Client\GuzzleClientFactory', 'getClient']
