services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Backend\:
    resource: '../Classes/*'

  # Temporary workaround until testing framework loads EXT:fluid in functional tests
  # @todo: Fix typo3/testing-framework and remove this
  TYPO3\CMS\Backend\View\BackendTemplateView:
    autoconfigure: false

  TYPO3\CMS\Backend\Template\ModuleTemplate:
    shared: false
    public: true

  TYPO3\CMS\Backend\History\RecordHistoryRollback:
    public: true
